# A configuration file for the Narrator module

bot:
  token:  # 0123456789:will_be_taken_from_.env
  allowed_usernames: ["durov"] # will be enriched from .env

utils:
  balcon:
    path: c:\bin\balcon.exe
  ffmpeg:
    path: c:\bin\ffmpeg.exe

to_txt:
  max_input_size: 5242880 # 5 * 2 ^ 20 == 5 MiB 