# A configuration file for the Narrator module

bot:
  token:  # 0123456789:will_be_taken_from_.env
  allowed_usernames: ["durov"] # will be enriched from .env

utils:
  balcon:
    path: c:\bin\balcon.exe
    defaults:
      ru:
        voice: Microsoft Irina Desktop
        speed: 8
        volume: 100
        pitch: 0
      en:
        voice: Microsoft Zira Desktop
        speed: 4
        volume: 100
        pitch: 0
  ffmpeg:
    path: c:\bin\ffmpeg.exe
  blb2txt:
    path: c:\bin\blb2txt.exe

text:
  max_input_size: 5242880 # 5 * 2 ^ 20 == 5 MiB 
  input_formats: [".epub", ".fb2", ".fb3", ".md", ".txt", ".doc", ".docx", ".rtf", ".html", ".htm"]

web_parser:
  sites:
    habr:
      url_re: https\://habr\.com/..(/company/[-\w]+/blog|/post|/news/t)/\d+
      lang: ru
      re:
        title: main h1[data-test-id="articleTitle"] span
        author: main a.tm-user-info__username
        publication_date: main div.tm-article-snippet__meta time
        text: "#post-content-body"